# Generated by Django 5.1.6 on 2025-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyforgeapp', '0016_alter_character_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='biography',
            field=models.TextField(default='no biography'),
        ),
    ]
