# Generated by Django 5.1.6 on 2025-04-15 21:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyforgeapp', '0017_character_biography'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='Barbarian', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='owners',
            field=models.ManyToManyField(related_name='characters', through='fantasyforgeapp.Ownership', to=settings.AUTH_USER_MODEL),
        ),
    ]
