name: deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: git pull
      run: |
        cd /home/django/project/Fantasy-Forge
        git fetch --all
        git checkout main
        git pull --all
    - name: installing dependencies and setup
      run: |
        cd /home/django/project/Fantasy-Forge/api
        source .venv/bin/activate
        pip install -r requirements.txt
        python manage.py flush --noinput --skip-checks
        python manage.py makemigrations --merge --noinput --skip-checks
        python manage.py migrate
        sudo pkill -9 gunicorn
        sudo systemctl start gunicorn
        deactivate
        cd ../frontend
        npm install
        npm install axios
        npm run build
